Limpeza de Dados
-

In [1]:
import pandas as pd

Importação dos dataframes

In [2]:
'''df2019 = pd.read_csv('../dados/2019.csv', low_memory=False, index_col=0)
df2020 = pd.read_csv('../dados/2020.csv', low_memory=False, index_col=0)'''

In [7]:
'''df2019.columns'''

Index(['Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)',
       'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',
       'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)',
       'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)',
       'RADIACAO GLOBAL (KJ/m²)',
       'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',
       'TEMPERATURA DO PONTO DE ORVALHO (°C)',
       'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)',
       'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)',
       'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)',
       'UMIDADE RELATIVA DO AR, HORARIA (%)',
       'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)',
       'VENTO, VELOCIDADE HORARIA (m/s)', 'REGIAO', 'UF', 'ESTACAO',
       'CODIGO (WMO)', 'LATITUDE', 'LONGITUDE', 'ALTITUDE',
       'DATA DE FUNDAC?O'],
      dtype='str')

In [6]:
'''df2020.columns'''

Index(['Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)',
       'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',
       'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)',
       'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)',
       'RADIACAO GLOBAL (Kj/m²)',
       'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',
       'TEMPERATURA DO PONTO DE ORVALHO (°C)',
       'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)',
       'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)',
       'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)',
       'UMIDADE RELATIVA DO AR, HORARIA (%)',
       'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)',
       'VENTO, VELOCIDADE HORARIA (m/s)', 'REGIAO', 'UF', 'ESTACAO',
       'CODIGO (WMO)', 'LATITUDE', 'LONGITUDE', 'ALTITUDE',
       'DATA DE FUNDACAO'],
      dtype='str')

In [8]:
'''df2019.reset_index(inplace=True)
df2020.reset_index(inplace=True)'''

União dos Dataframes

In [9]:
'''df_total = pd.concat(
    [df2019, df2020],
    ignore_index=True
)
df_total'''

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),...,REGIAO,UF,ESTACAO,CODIGO (WMO),LATITUDE,LONGITUDE,ALTITUDE,DATA DE FUNDAC?O,RADIACAO GLOBAL (Kj/m²),DATA DE FUNDACAO
0,2019/01/01,0000 UTC,0,"925,2","925,2","924,3",NaN,"21,4","19,7","21,8",...,N,TO,MATEIROS,A040,-10,-45,791,25/10/12,NaN,NaN
1,2019/01/01,0100 UTC,0,"925,6","925,6","925,1",NaN,"20,9","19,4","21,6",...,N,TO,MATEIROS,A040,-10,-45,791,25/10/12,NaN,NaN
2,2019/01/01,0200 UTC,0,"925,5","925,7","925,5",NaN,"20,4","19,2","20,9",...,N,TO,MATEIROS,A040,-10,-45,791,25/10/12,NaN,NaN
3,2019/01/01,0300 UTC,0,"925,1","925,5","925,1",NaN,"20,1","18,9","20,4",...,N,TO,MATEIROS,A040,-10,-45,791,25/10/12,NaN,NaN
4,2019/01/01,0400 UTC,0,"924,3","925,1","924,3",NaN,"20,1","18,9","20,3",...,N,TO,MATEIROS,A040,-10,-45,791,25/10/12,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10291987,2020/12/31,1900 UTC,0,"921,4","921,7","921,3",NaN,23,"19,4","24,7",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,"774,4",08/07/07
10291988,2020/12/31,2000 UTC,0,"922,2","922,2","921,4",NaN,"22,1","19,4","23,1",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,"217,8",08/07/07
10291989,2020/12/31,2100 UTC,0,"922,1","922,2","921,8",NaN,"21,3","19,4","22,1",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,34,08/07/07
10291990,2020/12/31,2200 UTC,0,"922,5","922,5","922,1",NaN,"20,7","19,2","21,3",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,NaN,08/07/07
10291991,2020/12/31,2300 UTC,0,"922,9",923,"922,5",NaN,"19,8",19,"20,7",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,NaN,08/07/07

Filtro Apenas Pernambuco

In [22]:
'''df_pernambuco = df_total[df_total['UF'] == 'PE']
df_pernambuco'''

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),...,REGIAO,UF,ESTACAO,CODIGO (WMO),LATITUDE,LONGITUDE,ALTITUDE,DATA DE FUNDAC?O,RADIACAO GLOBAL (Kj/m²),DATA DE FUNDACAO
43800,2019/01/01,0000 UTC,0,1013,1013,"1012,8",NaN,27,"22,2","27,1",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43801,2019/01/01,0100 UTC,0,"1012,8",1013,"1012,8",NaN,"26,7",22,"27,1",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43802,2019/01/01,0200 UTC,0,"1012,5","1012,8","1012,5",NaN,"26,6","22,1","26,8",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43803,2019/01/01,0300 UTC,0,"1011,8","1012,5","1011,8",NaN,"26,3",22,"26,7",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43804,2019/01/01,0400 UTC,0,"1011,4","1011,8","1011,4",NaN,"26,1","21,8","26,6",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10291987,2020/12/31,1900 UTC,0,"921,4","921,7","921,3",NaN,23,"19,4","24,7",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,"774,4",08/07/07
10291988,2020/12/31,2000 UTC,0,"922,2","922,2","921,4",NaN,"22,1","19,4","23,1",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,"217,8",08/07/07
10291989,2020/12/31,2100 UTC,0,"922,1","922,2","921,8",NaN,"21,3","19,4","22,1",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,34,08/07/07
10291990,2020/12/31,2200 UTC,0,"922,5","922,5","922,1",NaN,"20,7","19,2","21,3",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,NaN,08/07/07
10291991,2020/12/31,2300 UTC,0,"922,9",923,"922,5",NaN,"19,8",19,"20,7",...,NE,PE,GARANHUNS,A322,-8,-36,827,NaN,NaN,08/07/07

In [28]:
'''df_pernambuco.to_csv('../dados/df_pernambuco.csv')'''

In [ ]:
df_pernambuco = pd.read_csv('../dados/df_pernambuco.csv')

Filtro Apenas Recife

In [23]:
df_recife = df_pernambuco[df_pernambuco['ESTACAO'] == 'RECIFE']
df_recife

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),...,REGIAO,UF,ESTACAO,CODIGO (WMO),LATITUDE,LONGITUDE,ALTITUDE,DATA DE FUNDAC?O,RADIACAO GLOBAL (Kj/m²),DATA DE FUNDACAO
43800,2019/01/01,0000 UTC,0,1013,1013,"1012,8",NaN,27,"22,2","27,1",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43801,2019/01/01,0100 UTC,0,"1012,8",1013,"1012,8",NaN,"26,7",22,"27,1",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43802,2019/01/01,0200 UTC,0,"1012,5","1012,8","1012,5",NaN,"26,6","22,1","26,8",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43803,2019/01/01,0300 UTC,0,"1011,8","1012,5","1011,8",NaN,"26,3",22,"26,7",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
43804,2019/01/01,0400 UTC,0,"1011,4","1011,8","1011,4",NaN,"26,1","21,8","26,6",...,NE,PE,RECIFE,A301,-8,-34,11,22/12/04,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8491267,2020/12/31,1900 UTC,0,"1011,3","1011,3",1011,NaN,"26,8","22,5",27,...,NE,PE,RECIFE,A301,-8,-34,11,NaN,"717,2",22/12/04
8491268,2020/12/31,2000 UTC,0,"1011,6","1011,7","1011,3",NaN,"25,8","21,7","26,8",...,NE,PE,RECIFE,A301,-8,-34,11,NaN,"210,7",22/12/04
8491269,2020/12/31,2100 UTC,0,"1012,1","1012,1","1011,6",NaN,"26,2",22,"26,2",...,NE,PE,RECIFE,A301,-8,-34,11,NaN,"17,8",22/12/04
8491270,2020/12/31,2200 UTC,0,"1012,5","1012,5",1012,NaN,"26,3","21,8","26,3",...,NE,PE,RECIFE,A301,-8,-34,11,NaN,NaN,22/12/04
8491271,2020/12/31,2300 UTC,0,"1012,9","1012,9","1012,5",NaN,"26,4","21,9","26,5",...,NE,PE,RECIFE,A301,-8,-34,11,NaN,NaN,22/12/04

Limpeza de colunas

In [24]:
colunas_inuteis = ['DATA DE FUNDAC?O', 'RADIACAO GLOBAL (Kj/m²)', 'DATA DE FUNDACAO', 'ALTITUDE', 'LONGITUDE', 'LATITUDE', 'CODIGO (WMO)', 'ESTACAO', 'UF', 'REGIAO', 'RADIACAO GLOBAL (KJ/m²)']
df_recife.drop(columns = colunas_inuteis, inplace=True)
df_recife.reset_index(inplace=True, drop=True)
df_recife

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2019/01/01,0000 UTC,0,1013,1013,"1012,8",27,"22,2","27,1","26,9","22,4","22,1",76.0,75.0,75.0,114.0,"4,8","1,9"
1,2019/01/01,0100 UTC,0,"1012,8",1013,"1012,8","26,7",22,"27,1","26,6","22,2","21,9",76.0,74.0,76.0,122.0,"4,8","1,4"
2,2019/01/01,0200 UTC,0,"1012,5","1012,8","1012,5","26,6","22,1","26,8","26,5","22,2","21,9",76.0,76.0,76.0,123.0,"4,8","1,7"
3,2019/01/01,0300 UTC,0,"1011,8","1012,5","1011,8","26,3",22,"26,7","26,3","22,2",22,78.0,76.0,77.0,120.0,"4,3","1,3"
4,2019/01/01,0400 UTC,0,"1011,4","1011,8","1011,4","26,1","21,8","26,6","26,1","22,2","21,7",77.0,76.0,77.0,123.0,"4,4","1,2"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17539,2020/12/31,1900 UTC,0,"1011,3","1011,3",1011,"26,8","22,5",27,"26,2","23,8","22,3",83.0,77.0,77.0,124.0,"6,3","2,4"
17540,2020/12/31,2000 UTC,0,"1011,6","1011,7","1011,3","25,8","21,7","26,8","25,8","22,4","21,7",78.0,76.0,78.0,125.0,"6,2","2,4"
17541,2020/12/31,2100 UTC,0,"1012,1","1012,1","1011,6","26,2",22,"26,2","25,6","22,2","21,7",81.0,78.0,78.0,136.0,"5,8",2
17542,2020/12/31,2200 UTC,0,"1012,5","1012,5",1012,"26,3","21,8","26,3","26,1",22,"21,7",78.0,76.0,76.0,130.0,"5,3","1,8"
17543,2020/12/31,2300 UTC,0,"1012,9","1012,9","1012,5","26,4","21,9","26,5","26,3",22,"21,8",77.0,76.0,76.0,114.0,"6,1","1,7"

In [25]:
df_recife.info()

<class 'pandas.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 18 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Data                                                   17544 non-null  str
 1   Hora UTC                                               17544 non-null  str
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       17531 non-null  str
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  17531 non-null  str
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        17529 non-null  str
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       17529 non-null  str
 6   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           17531 non-null  str
 7   TEMPERATURA DO PONTO DE ORVALHO (°C)                   17531 non-null  str
 8   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             17529 non-null  str
 9   TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)             17529 non-null  str
 10  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       17529 non-null  str
 11  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       17529 non-null  str
 12  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               17529 non-null  float64
 13  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               17529 non-null  float64
 14  UMIDADE RELATIVA DO AR, HORARIA (%)                    17531 non-null  float64
 15  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   5990 non-null   float64
 16  VENTO, RAJADA MAXIMA (m/s)                             5954 non-null   str
 17  VENTO, VELOCIDADE HORARIA (m/s)                        5990 non-null   str
dtypes: float64(4), str(14)
memory usage: 2.4 MB

Ajuste do tipo da coluna Data

In [26]:
df_recife["Data"] = pd.to_datetime(df_recife["Data"], format="%Y/%m/%d", errors="coerce")

In [27]:
df_recife.to_csv('../dados/df_recife.csv')